baseURL: 'https://xaizone.eu'
languageCode: en
title: 'xaizone.eu'
enableRobotsTXT: true

markup:
  highlight:
    style: native

params:
  dateFormat: '2006-01-02'
  favicon: 'favicon.svg'
  stylesheet: 'style.css'
  postLimit: 7
  description: 'personal website of xaizone; a simple blog with good intentions'
  author: xaizone

taxonomies:
  tag: tags

outputs:
  section:
  - HTML
  taxonomy:
  - HTML
  term:
  - HTML

outputFormats:
  rss:
    mediaType: application/rss+xml
    basename: rss