baseURL: 'https://xaizone.eu'
languageCode: en
title: 'xaizone.eu'
enableRobotsTXT: true

params:
  dateFormat: '2006-01-02'
  favicon: 'favicon.svg'
  stylesheet: 'style.css'
  postLimit: 5
  description: 'personal website of xaizone; a simple blog with good intentions'
  author: xaizone

menu:
  social:
  - name: github
    url: 'https://github.com/xaizone'
  - name: twitter
    url: 'https://twitter.com/xaizone'
  - name: twitch
    url: 'https://twitch.tv/xaizone'
  - name: steam
    url: 'https://steamcommunity.com/id/xaizone'

taxonomies:
  tag: tags

outputs:
  section:
  - HTML
  taxonomy:
  - HTML
  term:
  - HTML

outputFormats:
  rss:
    mediaType: application/rss+xml
    basename: rss